# Test 2023-10-14 at 07:58:47

name: Test

on:
  push

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'main'

    - uses: actions/checkout@v3
      with:
        repository: philiprbrenan/DataTableText
        path: dtt

    - name: Cpan
      run:  sudo cpan install -T Data::Dump Data::Table::Text
    - name: Ubuntu update
      run:  sudo apt update

    - name: Verilog installation
      run:  sudo apt -y install iverilog

    - name: Test Perl
      run:
        perl Zesal.pm

    - name: Test Verilog
      run:
        rm -f Zesal; iverilog -Iincludes/ -g2012 -o Zesal Zesal.sv Zesal.tb && timeout 1m ./Zesal
